### ISSUE TITLE
Figure out US Tax Status

### ISSUE THREAD

**Issue by iggysiggy** [oxfordglobal/turkey-conference#2]
We should figure out how incorporating will affect the tax status of Americans working on the project.

**Comment by iggysiggy** [comment]
We will have to file form 5471, along with other forms for the various partnerships in which we have a stake.

**Comment by esoli** [comment]
Who should file this form? Will non-US citizens need to as well?

**Comment by iggysiggy** [comment]
No, it will just be me until other US citizens show up.

**Comment by esoli** [comment]
Coolio.
